spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/xepdb1
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

#logging:
#  level:
#    root: info
#  file:
#    name: myapp.log
